/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import LoebMeasure.Mathlib.MeasureTheory.OuterMeasure.OfAddContent
import LoebMeasure.Measure.Construction

/-!
# The Loeb measure

The Carathéodory extension of the internal content: a complete probability measure on
the ultraproduct, agreeing with the internal content on every realized internal set.

Everything substantive was proved upstream of this module. What remains is to feed
C5's σ-subadditivity and I3's set ring into `MeasureTheory.AddContent.measureCaratheodory`
and read off the four consequences. No new measure-theoretic argument occurs here.

## The two hypotheses, and where each is needed

Throughout, "hypothesis" means one of the two *explicit* arguments `hX` and `hU`. The
stage instances `[∀ i, MeasurableSpace (X i)]`, `[∀ i, Finite (X i)]` and
`[∀ i, MeasurableSingletonClass (X i)]` are ambient on the whole module — the content is
built from the stage measures, so everything here needs them — and the claims below are
about `hX` and `hU` only.

Of those two, the construction is deliberately split so that the σ-algebra does **not**
inherit the measure's:

* `loebMeasurableSpace` takes `hX` alone, through the content's packaging. The
  Carathéodory σ-algebra of an induced outer measure exists whether or not that outer
  measure is well behaved, so **countable incompleteness plays no part in defining the
  σ-algebra**;
* `loebMeasure` additionally takes `hU`, since σ-subadditivity — the input that makes
  the extension a measure rather than merely an outer measure — is where C5 consumed
  saturation.

The one declaration here that genuinely needs *nothing*, stage instances included, is
`isSetSemiring_carriers`, which is why its instances are `omit`ted.

Both hypotheses are `Prop`-valued, so proof irrelevance makes any two choices of `hX`
give the *same* σ-algebra definitionally; there is no coherence obligation to discharge
and no need for a canonical proof term.

## Why completeness is wrapped rather than proved

`(loebMeasure hU hX).IsComplete` is the mirror directory's
`MeasureTheory.AddContent.measureCaratheodory_isComplete` applied to this content, as
ADR-0003 requires: the argument is generic — it holds for any σ-subadditive content on a
set semiring, with no finiteness or probability hypotheses — so reproducing it here
would duplicate a result the project also intends to upstream (#10). Completeness comes
from the *construction*, not from anything specific to Loeb measure.

Note what this means for the σ-algebra: `loebMeasurableSpace` is the **full** Carathéodory
σ-algebra, not the σ-algebra generated by the internal sets, which is why completeness is
available at all. `AddContent.measure` — mathlib's `trim`med variant targeting a
generated σ-algebra — is for that reason not used (ADR-0003).

## Scope

The construction and its immediate consequences. The internal-mod-null approximation
(`loebMeasurable_iff_internal_mod_null`) is C7/C8: it is not a formal consequence of the
construction but genuine approximation work, consuming finite total mass and the
increasing-envelope diagonal argument. Atomlessness is C9.
-/

namespace Loeb

open Filter MeasureTheory
open scoped ENNReal

variable {ι : Type*} {X : ι → Type*} [∀ i, MeasurableSpace (X i)] [∀ i, Finite (X i)]
  [∀ i, MeasurableSingletonClass (X i)] {U : Ultrafilter ι}

omit [∀ i, MeasurableSpace (X i)] [∀ i, Finite (X i)] [∀ i, MeasurableSingletonClass (X i)] in
/-- The set semiring the extension consumes: I3's set ring of realized internal sets,
weakened to a semiring, which is the form `AddContent.measureCaratheodory` asks for.

`private`: every consumer is in this module. There is no coherence reason to name it —
`IsSetSemiring` is a `Prop`, so proof irrelevance already makes any two proofs
interchangeable — and it is named purely so the five constructions below read cleanly.
Should it acquire a consumer outside this module, it belongs beside
`InternalSet.isSetRing_carriers` in I3 rather than here.

It needs **no stage structure at all** — not measurability, not finiteness — since it is
I3's Boolean algebra of internal sets and nothing more; every stage instance is omitted
to make that visible. -/
private theorem isSetSemiring_carriers :
    IsSetSemiring (InternalSet.carriers U X) :=
  InternalSet.isSetRing_carriers.isSetSemiring

/-- **The Loeb outer measure**: the outer measure induced by the internal content on the
realized internal sets.

Public as of C7b, which is the consumer this definition's earlier `private` note
anticipated: C7b unfolds the infimum over countable internal covers and, using C7a's
envelope, rewrites it as an infimum over *single* internal supersets. Reaching that
representation through `loebMeasurableSpace` instead would be an abstraction leak.

Takes `hX` and not `hU`, for the same reason `loebMeasurableSpace` does: an induced outer
measure exists whether or not the content is σ-subadditive. -/
noncomputable def loebOuterMeasure (hX : ∀ i, Nonempty (X i)) :
    OuterMeasure (Ultraproduct U X) :=
  inducedOuterMeasure (fun s (_ : s ∈ InternalSet.carriers U X) ↦ internalAddContent hX s)
    isSetSemiring_carriers.empty_mem addContent_empty

/-- **The Loeb σ-algebra**: the Carathéodory σ-algebra of the outer measure induced by
the internal content.

Of the two explicit hypotheses it takes only `hX`, **not** `hU`: countable incompleteness
enters only when the extension is shown to be a measure. The stage instances
(`MeasurableSpace`, `Finite`, `MeasurableSingletonClass`) are of course still required,
since the content is built from the stage measures.

`@[reducible]` because mathlib's linter asks it of any definition whose result is a class,
and this project promotes warnings to errors. It is not needed for `loebMeasure` to
elaborate at this space: a semireducible `def` unfolds during unification just as well. -/
@[reducible]
noncomputable def loebMeasurableSpace (hX : ∀ i, Nonempty (X i)) :
    MeasurableSpace (Ultraproduct U X) :=
  (loebOuterMeasure hX).caratheodory

/-- **The Loeb measure**: the Carathéodory extension of the internal content.

Both hypotheses are consumed exactly once each: `hX` packages the content
(`internalAddContent`), and `hU` supplies σ-subadditivity
(`internalAddContent_isSigmaSubadditive`). -/
noncomputable def loebMeasure (hU : (U : Filter ι).IsCountablyIncomplete)
    (hX : ∀ i, Nonempty (X i)) :
    @Measure (Ultraproduct U X) (loebMeasurableSpace hX) :=
  (internalAddContent hX).measureCaratheodory isSetSemiring_carriers
    (internalAddContent_isSigmaSubadditive hU hX)

/-- **The Loeb measure agrees with the Loeb outer measure on every set** — including
non-measurable ones, since `measureCaratheodory` is the induced outer measure verbatim
and only its σ-algebra is cut down.

Deliberately **not** `@[simp]`: `loebMeasure_internal` is the preferred normal form, and
rewriting every `loebMeasure` into an outer measure would defeat it. This is the door
into the cover representation, opened by hand where C7b needs it. -/
theorem loebMeasure_eq_loebOuterMeasure (hU : (U : Filter ι).IsCountablyIncomplete)
    (hX : ∀ i, Nonempty (X i)) (s : Set (Ultraproduct U X)) :
    loebMeasure hU hX s = loebOuterMeasure hX s :=
  rfl

/-- **The Loeb measure extends the internal content.**

The defining property, and the only one that mentions internal sets. Every realized
internal set lies in the semiring, where `AddContent.measureCaratheodory_eq` says the
extension agrees with the content. -/
@[simp]
theorem loebMeasure_internal (hU : (U : Filter ι).IsCountablyIncomplete)
    (hX : ∀ i, Nonempty (X i)) (A : InternalSet U X) :
    loebMeasure hU hX (InternalSet.carrier A) = internalContent U A :=
  (AddContent.measureCaratheodory_eq _ isSetSemiring_carriers _
    (InternalSet.carrier_mem_carriers A)).trans (internalAddContent_carrier hX A)

/-- Realized internal sets are Loeb measurable.

Immediate from `AddContent.measureCaratheodory`'s target σ-algebra containing the
semiring, but worth naming: it is what lets `loebMeasure_internal` be read as a statement
about a measurable set. -/
theorem measurableSet_internal (hX : ∀ i, Nonempty (X i)) (A : InternalSet U X) :
    MeasurableSet[loebMeasurableSpace hX] (InternalSet.carrier A) :=
  AddContent.isCaratheodory_inducedOuterMeasure_of_mem isSetSemiring_carriers
    (internalAddContent hX) (InternalSet.carrier_mem_carriers A)

/-- **The Loeb measure is a probability measure.**

This is where the total mass of the stagewise normalized counting measures is cashed in:
`⊤` realizes all of the ultraproduct, and its content is the ultralimit of the constant
`1`. Nonemptiness of the fibers is genuinely used — on empty stages the stage measures
have total mass `0`, not `1` (ADR-0002). -/
instance isProbabilityMeasure_loebMeasure (hU : (U : Filter ι).IsCountablyIncomplete)
    (hX : ∀ i, Nonempty (X i)) : IsProbabilityMeasure (loebMeasure hU hX) := by
  haveI : ∀ i, Nonempty (X i) := hX
  refine ⟨?_⟩
  rw [← InternalSet.carrier_top (U := U) (X := X), loebMeasure_internal, internalContent_top]

/-- **The Loeb measure is complete.**

A wrapper, not a proof: the argument is the generic
`MeasureTheory.AddContent.measureCaratheodory_isComplete`, which needs no finiteness or
probability hypotheses. See the module docstring and ADR-0003 for why duplicating it
here would be a mistake. -/
instance isComplete_loebMeasure (hU : (U : Filter ι).IsCountablyIncomplete)
    (hX : ∀ i, Nonempty (X i)) : (loebMeasure hU hX).IsComplete :=
  (internalAddContent hX).measureCaratheodory_isComplete isSetSemiring_carriers
    (internalAddContent_isSigmaSubadditive hU hX)

/-! ### API tests -/

section Tests

variable (hU : (U : Filter ι).IsCountablyIncomplete) (hX : ∀ i, Nonempty (X i))

/-- **The defining property**, by `simp`. -/
example (A : InternalSet U X) :
    loebMeasure hU hX (InternalSet.carrier A) = internalContent U A := by
  simp

/-- The empty internal set is null, through the defining property rather than through
`measure_empty` — a check that the two agree. -/
example : loebMeasure hU hX (InternalSet.carrier (⊥ : InternalSet U X)) = 0 := by
  simp

/-- Total mass one, from the instance. -/
example : loebMeasure hU hX Set.univ = 1 := measure_univ

/-- **Completeness is usable as an instance**: a null set is measurable, with no
internality hypothesis. This is the shape C7/C8 will lean on. -/
example (s : Set (Ultraproduct U X)) (hs : loebMeasure hU hX s = 0) :
    MeasurableSet[loebMeasurableSpace hX] s :=
  measurableSet_of_null hs

/-- **The σ-algebra needs no countable incompleteness.** This statement is well formed
and provable with `hU` nowhere in scope — the section variable is not included, because
nothing here mentions it — which is the stratification the module docstring claims. -/
example (hX : ∀ i, Nonempty (X i)) (A : InternalSet U X) :
    MeasurableSet[loebMeasurableSpace hX] (InternalSet.carrier A) :=
  measurableSet_internal hX A

/-- Loeb measure of a realized internal set is at most one — the bound coming from the
content, not from the probability instance. -/
example (A : InternalSet U X) : loebMeasure hU hX (InternalSet.carrier A) ≤ 1 := by
  rw [loebMeasure_internal]
  exact internalContent_le_one A

/-- **A genuinely dependent family** of stage spaces, with the hyperfilter on `ℕ`
supplying countable incompleteness. -/
example (U : Ultrafilter ℕ) (hU : (U : Filter ℕ).IsCountablyIncomplete)
    (A : InternalSet U fun i ↦ Fin (i + 1)) :
    loebMeasure hU (fun _ ↦ ⟨0⟩) (InternalSet.carrier A)
      = internalContent U A := by
  simp

end Tests

end Loeb
